### ISSUE TITLE
Delete `.DS_Store` and add `.DS_Store` to `.gitignore`

### ISSUE THREAD

**Issue by glyh** [AbigaleD/AbigaleD.github.io#1]
As per wiki, `.DS_Store` is a file used by MacOS to keep track of some information. That shouldn't belong to a git repo and has nothing to do with Jekyll

**Comment by AbigaleD** [comment]
Thanks for your feedback.I didn't expect anyone to check/pull this... .DS_Store seems to be of no use.I will see if there is a way to turn it off on macos permantly （after a long while maybe,since it is not urgent)
